export type ReportFinding = {
  label: string;
  status: "pass" | "warn" | "fail" | "info";
  detail: string;
};

export type ReportCategory = {
  score: number;
  summary: string;
  findings: ReportFinding[];
};

export type ReportRecommendation = {
  priority: "high" | "medium" | "low";
  area: string;
  title: string;
  action: string;
  findingLabel?: string;
};

export type ReportResult = {
  url: string;
  finalUrl: string;
  fetchedAt: string;
  title: string;
  focusTopic?: string;
  seo: ReportCategory;
  relevance: ReportCategory;
  freshness: ReportCategory;
  readability: ReportCategory;
  design: ReportCategory;
  reachability: ReportCategory;
  conversion: ReportCategory;
  overallScore: number;
  recommendations: ReportRecommendation[];
};

function slugFromUrl(url: string) {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return "website";
  }
}

function formatCategory(name: string, category: ReportCategory) {
  const lines = [
    `## ${name}`,
    "",
    `**Score:** ${category.score}/100`,
    "",
    category.summary,
    "",
    "### Findings",
    "",
  ];

  for (const finding of category.findings) {
    lines.push(
      `- **${finding.label}** (${finding.status}): ${finding.detail}`,
    );
  }

  lines.push("");
  return lines;
}

export function buildMarkdownReport(
  result: ReportResult,
  topic?: string,
): string {
  const analyzedAt = new Date(result.fetchedAt).toLocaleString("en-US", {
    dateStyle: "long",
    timeStyle: "short",
  });

  const focus = topic?.trim() || result.focusTopic?.trim() || "";

  const lines = [
    "# Website analysis report",
    "",
    `Generated by Macomb Code · ${analyzedAt}`,
    "",
    `**Page:** ${result.title || "Untitled"}`,
    `**URL:** ${result.finalUrl}`,
    `**Requested URL:** ${result.url}`,
  ];

  if (focus) {
    lines.push(`**Focus topic:** ${focus}`);
  }

  lines.push(
    "",
    "## Scores",
    "",
    `| Category | Score |`,
    `| --- | ---: |`,
    `| Overall | ${result.overallScore} |`,
    `| Reachability | ${result.reachability.score} |`,
    `| Conversion | ${result.conversion.score} |`,
    `| Relevance | ${result.relevance.score} |`,
    `| SEO | ${result.seo.score} |`,
    `| Readability | ${result.readability.score} |`,
    `| Design | ${result.design.score} |`,
    `| Freshness | ${result.freshness.score} |`,
    "",
    "## Recommended updates",
    "",
  );

  if (result.recommendations.length === 0) {
    lines.push("_No recommendations generated._", "");
  } else {
    result.recommendations.forEach((item, index) => {
      lines.push(
        `### ${index + 1}. ${item.title}`,
        "",
        `**Priority:** ${item.priority} · **Area:** ${item.area}`,
        "",
        item.action,
        "",
      );
    });
  }

  lines.push(
    ...formatCategory("Can customers reach you", result.reachability),
    ...formatCategory("Conversion basics", result.conversion),
    ...formatCategory("Relevance", result.relevance),
    ...formatCategory("SEO", result.seo),
    ...formatCategory("Readability", result.readability),
    ...formatCategory("Design", result.design),
    ...formatCategory("Freshness", result.freshness),
    "---",
    "",
    "_Want help fixing these? Book a free 15-minute call at macombcode.com/#contact_",
    "",
    "_Report generated at macombcode.com/analyze_",
    "",
  );

  return lines.join("\n");
}

export function reportFilename(result: ReportResult, extension: string) {
  const stamp = new Date(result.fetchedAt).toISOString().slice(0, 10);
  return `macomb-code-report-${slugFromUrl(result.finalUrl)}-${stamp}.${extension}`;
}

export function downloadTextFile(
  content: string,
  filename: string,
  mimeType: string,
) {
  const blob = new Blob([content], { type: mimeType });
  const href = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = href;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(href);
}
